{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 数据和包导入"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "import pickle\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import roc_curve, auc\n",
    "from sklearn.metrics import precision_recall_curve\n",
    "from sklearn.metrics import average_precision_score\n",
    "from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, balanced_accuracy_score\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from sklearn.metrics import classification_report\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "plt.rcParams['figure.dpi'] = 80 \n",
    "plt.rcParams.update({'font.size': 18})\n",
    "\n",
    "\n",
    "roc_auc_values = []\n",
    "precision_values = []\n",
    "recall_values = []\n",
    "f1_values = []\n",
    "accuracy_values = []\n",
    "\n",
    "with open('metrics/inner_metrics_list.pkl', 'rb') as f:\n",
    "    inner_metrics_list = pickle.load(f)\n",
    "with open('metrics/out_metrics_list.pkl', 'rb') as f:\n",
    "    out_metrics_list = pickle.load(f)\n",
    "with open('metrics/hold_metrics_list.pkl', 'rb') as f:\n",
    "    hold_metrics_list = pickle.load(f)\n",
    "with open('metrics/best_params_list.pkl', 'rb') as f:\n",
    "    best_params_list = pickle.load(f)\n",
    "with open('metrics/hold_params_list.pkl', 'rb') as f:\n",
    "    hold_params_list = pickle.load(f)\n",
    "with open('metrics/best_model_item.pkl', 'rb') as f:\n",
    "    best_model_item = pickle.load(f)\n",
    "\n",
    "\n",
    "\n",
    "model_name = ['SVM', 'AdaBoost', 'RandomForest', 'Stacking']\n",
    "\n",
    "model_num = 4\n",
    "epoch_num = 100 #Epoch调整了需要修改\n",
    "outer_num = 5\n",
    "inner_num = 3"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 模型信息"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "best_model = best_model_item['clf']\n",
    "print(best_model_item['params'])\n",
    "best_model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "y_true = best_model_item['eval'][0]\n",
    "y_scores = best_model_item['eval'][1]\n",
    "print([\n",
    "    precision_score(y_true, (y_scores > 0.5).astype(int), zero_division = 1),\n",
    "    classification_report(y_true, (y_scores > 0.5).astype(int), output_dict=True)['macro avg']['recall'],\n",
    "    f1_score(y_true, (y_scores > 0.5).astype(int),zero_division = 1),\n",
    "    balanced_accuracy_score(y_true, (y_scores > 0.5).astype(int)),\n",
    "    roc_auc_score(y_true, y_scores)\n",
    "])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 四个模型外循环的ROC 曲线对比图"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "len(out_metrics_list) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import roc_curve, auc\n",
    "import scipy.stats as stats\n",
    "\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "\n",
    "\n",
    "model_info = [\n",
    "    {\"name\": \"SVM\", \"color\": \"b\"},\n",
    "    {\"name\": \"AdaBoost\", \"color\": \"g\"},\n",
    "    {\"name\": \"RandomForest\", \"color\": \"r\"},\n",
    "    {\"name\": \"Stacking\", \"color\": \"c\"},\n",
    "]\n",
    "\n",
    "\n",
    "roc_data = {model[\"name\"]: {\"fprs\": [], \"tprs\": []} for model in model_info}\n",
    "\n",
    "\n",
    "partition_size = epoch_num * outer_num\n",
    "for model_idx, model in enumerate(model_info):\n",
    "    start_idx = model_idx * partition_size\n",
    "    end_idx = (model_idx + 1) * partition_size\n",
    "    model_metrics = out_metrics_list[start_idx:end_idx]\n",
    "\n",
    "\n",
    "    tprs = []\n",
    "    mean_tpr = np.zeros(100)\n",
    "    base_fpr = np.linspace(0, 1, 100)\n",
    "\n",
    "\n",
    "    for i in range(epoch_num * outer_num):\n",
    "        y_test_outer, y_pred_prob_outer = model_metrics[i]\n",
    "        fpr, tpr, _ = roc_curve(y_test_outer, y_pred_prob_outer)\n",
    "        tpr = np.interp(base_fpr, fpr, tpr)\n",
    "        tpr[0] = 0.0\n",
    "        tprs.append(tpr)\n",
    "        mean_tpr += tpr\n",
    "\n",
    "    mean_tpr /= epoch_num * outer_num\n",
    "    mean_tpr[-1] = 1.0\n",
    "    mean_auc = auc(base_fpr, mean_tpr)\n",
    "    std_auc = np.std([auc(base_fpr, tpr) for tpr in tprs])\n",
    "    std_tpr = np.std(tprs, axis=0)\n",
    "\n",
    "    roc_data[model[\"name\"]][\"base_fpr\"] = base_fpr\n",
    "    roc_data[model[\"name\"]][\"mean_tpr\"] = mean_tpr\n",
    "    roc_data[model[\"name\"]][\"mean_auc\"] = mean_auc\n",
    "    roc_data[model[\"name\"]][\"std_auc\"] = std_auc\n",
    "    roc_data[model[\"name\"]][\"std_tpr\"] = std_tpr\n",
    "\n",
    "\n",
    "for model in model_info:\n",
    "    base_fpr = roc_data[model[\"name\"]][\"base_fpr\"]\n",
    "    mean_tpr = roc_data[model[\"name\"]][\"mean_tpr\"]\n",
    "    mean_auc = roc_data[model[\"name\"]][\"mean_auc\"]\n",
    "    std_auc = roc_data[model[\"name\"]][\"std_auc\"]\n",
    "    std_tpr = roc_data[model[\"name\"]][\"std_tpr\"]\n",
    "\n",
    "    plt.plot(\n",
    "        base_fpr,\n",
    "        mean_tpr,\n",
    "        color=model[\"color\"],\n",
    "        label=f'{model[\"name\"]} (AUC = {mean_auc:.2f} ± {std_auc:.2f})',\n",
    "    )\n",
    "    tprs_upper = np.minimum(mean_tpr + std_tpr, 1)\n",
    "    tprs_lower = np.maximum(mean_tpr - std_tpr, 0)\n",
    "    plt.fill_between(base_fpr, tprs_lower, tprs_upper, color=model[\"color\"], alpha=0.2)\n",
    "\n",
    "\n",
    "plt.plot([0, 1], [0, 1], linestyle=\"--\", color=\"k\", lw=2, label=\"Random\")\n",
    "plt.xlim([0.0, 1.0])\n",
    "plt.ylim([0.0, 1.05])\n",
    "plt.xlabel(\"False Positive Rate\")\n",
    "plt.ylabel(\"True Positive Rate\")\n",
    "plt.title(\"Average ROC Curves on the Outer loop\", fontsize=16)\n",
    "plt.legend(loc='lower right', bbox_to_anchor=(0.999, 0.01), fontsize='xx-small')\n",
    "plt.grid()\n",
    "\n",
    "plt.savefig(\"image/roc_curves.png\", dpi=600, bbox_inches='tight')\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Holdout Set ROC 对比"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from sklearn.metrics import roc_curve, auc\n",
    "import scipy.stats as stats\n",
    "\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "\n",
    "model_info = [\n",
    "    {\"name\": \"SVM\", \"color\": \"b\"},\n",
    "    {\"name\": \"AdaBoost\", \"color\": \"g\"},\n",
    "    {\"name\": \"RandomForest\", \"color\": \"r\"},\n",
    "    {\"name\": \"Stacking\", \"color\": \"c\"},\n",
    "]\n",
    "\n",
    "roc_data_holdout = {model[\"name\"]: {\"fprs\": [], \"tprs\": []} for model in model_info}\n",
    "\n",
    "partition_size = epoch_num\n",
    "for model_idx, model in enumerate(model_info):\n",
    "    start_idx = model_idx * partition_size\n",
    "    end_idx = (model_idx + 1) * partition_size\n",
    "    model_metrics = hold_metrics_list[start_idx:end_idx]\n",
    "\n",
    "    tprs = []\n",
    "    mean_tpr = np.zeros(100)\n",
    "    base_fpr = np.linspace(0, 1, 100)\n",
    "\n",
    "    for i in range(epoch_num):\n",
    "        y_test_holdout, y_pred_prob_holdout = model_metrics[i]\n",
    "        fpr, tpr, _ = roc_curve(y_test_holdout, y_pred_prob_holdout)\n",
    "        tpr = np.interp(base_fpr, fpr, tpr)\n",
    "        tpr[0] = 0.0\n",
    "        tprs.append(tpr)\n",
    "        mean_tpr += tpr\n",
    "\n",
    "    mean_tpr /= epoch_num\n",
    "    mean_tpr[-1] = 1.0\n",
    "    mean_auc = auc(base_fpr, mean_tpr)\n",
    "    std_auc = np.std([auc(base_fpr, tpr) for tpr in tprs])\n",
    "    std_tpr = np.std(tprs, axis=0)\n",
    "\n",
    "    roc_data_holdout[model[\"name\"]][\"base_fpr\"] = base_fpr\n",
    "    roc_data_holdout[model[\"name\"]][\"mean_tpr\"] = mean_tpr\n",
    "    roc_data_holdout[model[\"name\"]][\"mean_auc\"] = mean_auc\n",
    "    roc_data_holdout[model[\"name\"]][\"std_auc\"] = std_auc\n",
    "    roc_data_holdout[model[\"name\"]][\"std_tpr\"] = std_tpr\n",
    "\n",
    "for model in model_info:\n",
    "    base_fpr = roc_data_holdout[model[\"name\"]][\"base_fpr\"]\n",
    "    mean_tpr = roc_data_holdout[model[\"name\"]][\"mean_tpr\"]\n",
    "    mean_auc = roc_data_holdout[model[\"name\"]][\"mean_auc\"]\n",
    "    std_auc = roc_data_holdout[model[\"name\"]][\"std_auc\"]\n",
    "    std_tpr = roc_data_holdout[model[\"name\"]][\"std_tpr\"]\n",
    "\n",
    "    plt.plot(\n",
    "        base_fpr,\n",
    "        mean_tpr,\n",
    "        color=model[\"color\"],\n",
    "        label=f'{model[\"name\"]} (AUC = {mean_auc:.2f} ± {std_auc:.2f})',\n",
    "    )\n",
    "    tprs_upper = np.minimum(mean_tpr + std_tpr, 1)\n",
    "    tprs_lower = np.maximum(mean_tpr - std_tpr, 0)\n",
    "    plt.fill_between(base_fpr, tprs_lower, tprs_upper, color=model[\"color\"], alpha=0.2)\n",
    "\n",
    "# Plot settings\n",
    "plt.plot([0, 1], [0, 1], linestyle=\"--\", color=\"k\", lw=2, label=\"Random\")\n",
    "plt.xlim([0.0, 1.0])\n",
    "plt.ylim([0.0, 1.05])\n",
    "plt.xlabel(\"False Positive Rate\")\n",
    "plt.ylabel(\"True Positive Rate\")\n",
    "plt.title(\"Average ROC Curves on the Test Set\", fontsize=16)\n",
    "plt.legend(loc='lower right', bbox_to_anchor=(0.999, 0.01), fontsize='xx-small')  # 修改了这行\n",
    "plt.grid()\n",
    "\n",
    "plt.savefig(\"image/hold_roc_curves.png\", dpi=600, bbox_inches='tight')\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import confusion_matrix\n",
    "\n",
    "for model_idx, model in enumerate(model_info):\n",
    "    start_idx = model_idx * partition_size\n",
    "    end_idx = (model_idx + 1) * partition_size\n",
    "    model_metrics = hold_metrics_list[start_idx:end_idx]\n",
    "\n",
    "    specificity_values = []\n",
    "\n",
    "    for i in range(epoch_num):\n",
    "        y_test_holdout, y_pred_prob_holdout = model_metrics[i]\n",
    "        y_pred_holdout = (y_pred_prob_holdout > 0.5).astype(int)  \n",
    "        tn, fp, fn, tp = confusion_matrix(y_test_holdout, y_pred_holdout).ravel()\n",
    "\n",
    "        specificity = tn / (tn + fp)\n",
    "        specificity_values.append(specificity)\n",
    "\n",
    "    print(f\"{model['name']}:\")\n",
    "    print(f\"  Specificity: {np.mean(specificity_values):.3f} ± {np.std(specificity_values):.3f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 每个模型循环epoch次,选出前epoch个效果最好的index就是该模型最好的,找到index推导参数"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import confusion_matrix\n",
    "\n",
    "\n",
    "def calculate_sensitivity(y_true, y_pred):\n",
    "    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()\n",
    "    sensitivity = tp / (tp + fn)\n",
    "    return sensitivity\n",
    "\n",
    "def calculate_specificity(y_true, y_pred):\n",
    "    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()\n",
    "    specificity = tn / (tn + fp)\n",
    "    return specificity\n",
    "\n",
    "metric_names = ['Sensitivity', 'Specificity', 'Balanced_Accuracy', 'AUC']\n",
    "\n",
    "iteration_dataframes = []\n",
    "\n",
    "for i, metrics in enumerate(hold_metrics_list):\n",
    "    iteration_metrics = [i + 1]\n",
    "\n",
    "    y_true = metrics[0]\n",
    "    y_scores = metrics[1]\n",
    "    iteration_metrics.extend([\n",
    "        calculate_sensitivity(y_true, (y_scores > 0.5).astype(int)),\n",
    "        calculate_specificity(y_true, (y_scores > 0.5).astype(int)),\n",
    "        balanced_accuracy_score(y_true, (y_scores > 0.5).astype(int)),\n",
    "        roc_auc_score(y_true, y_scores)\n",
    "    ])\n",
    "    tn, fp, fn, tp = confusion_matrix(y_true, (y_scores > 0.5).astype(int)).ravel()\n",
    "\n",
    "    iteration_dataframe = pd.DataFrame([iteration_metrics], columns=['Iteration'] + metric_names)\n",
    "\n",
    "    iteration_dataframes.append(iteration_dataframe)\n",
    "\n",
    "df_metrics = pd.concat(iteration_dataframes, ignore_index=True)\n",
    "\n",
    "df_metrics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "print(tn, fp, fn, tp)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "best_auc_indices = []\n",
    "\n",
    "for i in range(0, len(df_metrics), epoch_num):\n",
    "\n",
    "    group_data = df_metrics.iloc[i:i + epoch_num]\n",
    "\n",
    "    best_auc_index = group_data['AUC'].idxmax()\n",
    "\n",
    "    best_auc_indices.append(best_auc_index)\n",
    "\n",
    "print(\"Indices with the highest AUC for each group:\")\n",
    "print(best_auc_indices)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Hold Out不同模型雷达对比"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "df = pd.DataFrame(df_metrics)\n",
    "\n",
    "average_values = df.groupby(df.index // (epoch_num)).mean()\n",
    "average_values = average_values.iloc[:,1:].T\n",
    "average_values.columns = ['SVM','Adaboost','RF','Stacking']\n",
    "\n",
    "std_dev = df.groupby(df.index // (epoch_num)).std()\n",
    "std_dev = std_dev.iloc[:,1:].T\n",
    "std_dev.columns = ['SVM','Adaboost','RF','Stacking']\n",
    "\n",
    "average_values = average_values.applymap('{:.2f}'.format) \n",
    "std_dev = std_dev.applymap('{:.2f}'.format) \n",
    "\n",
    "result = average_values + ' ± ' + std_dev\n",
    "\n",
    "result = result.T\n",
    "\n",
    "result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from sklearn.metrics import confusion_matrix, balanced_accuracy_score, roc_auc_score\n",
    "\n",
    "metric_names = ['Specificity', 'Sensitivity','AUC','Balanced Accuracy']\n",
    "\n",
    "iteration_dataframes = []\n",
    "\n",
    "for i, metrics in enumerate(hold_metrics_list):\n",
    "    iteration_metrics = [i + 1]  \n",
    "    \n",
    "    y_true = metrics[0]\n",
    "    y_pred = (metrics[1] > 0.5).astype(int)\n",
    "    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()\n",
    "    \n",
    "    iteration_metrics.extend([\n",
    "        tn / (tn + fp),  \n",
    "        classification_report(y_true, y_pred, output_dict=True)['macro avg']['recall'], \n",
    "        balanced_accuracy_score(y_true, y_pred),\n",
    "        roc_auc_score(y_true, metrics[1])  \n",
    "    ])\n",
    "    \n",
    "    iteration_dataframes.append(pd.DataFrame([iteration_metrics], columns=['Iteration'] + metric_names))\n",
    "\n",
    "\n",
    "df_metrics = pd.concat(iteration_dataframes, ignore_index=True)\n",
    "\n",
    "average_values = df_metrics.groupby(df_metrics.index // epoch_num).mean()\n",
    "average_values = average_values.iloc[:,1:].T\n",
    "average_values.columns = ['SVM','Adaboost','RF','Stacking']\n",
    "\n",
    "labels = np.array(average_values.index.tolist())\n",
    "data1 = average_values['SVM'].values\n",
    "data2 = average_values['Adaboost'].values\n",
    "data3 = average_values['RF'].values\n",
    "data4 = average_values['Stacking'].values\n",
    "\n",
    "data1 = np.concatenate((data1, [data1[0]]))\n",
    "data2 = np.concatenate((data2, [data2[0]]))\n",
    "data3 = np.concatenate((data3, [data3[0]]))\n",
    "data4 = np.concatenate((data4, [data4[0]]))\n",
    "\n",
    "angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)\n",
    "angles = np.concatenate((angles, [angles[0]]))\n",
    "\n",
    "fig = plt.figure(figsize=(8, 8))\n",
    "ax = fig.add_subplot(111, polar=True)\n",
    "\n",
    "ax.plot(angles, data1, 'o-', linewidth=2, label='SVM', color='#e41a1c')\n",
    "ax.fill(angles, data1, color='#e41a1c', alpha=0.2)\n",
    "ax.plot(angles, data2, 'o-', linewidth=2, label='Adaboost', color='#377eb8')\n",
    "ax.fill(angles, data2, color='#377eb8', alpha=0.2)\n",
    "ax.plot(angles, data3, 'o-', linewidth=2, label='RF', color='#4daf4a')\n",
    "ax.fill(angles, data3, color='#4daf4a', alpha=0.2)\n",
    "ax.plot(angles, data4, 'o-', linewidth=2, label='Stacking', color='#984ea3')\n",
    "ax.fill(angles, data4, color='#984ea3', alpha=0.2)\n",
    "\n",
    "ax.set_thetagrids(angles[:-1] * 180/np.pi, labels)\n",
    "ax.set_rlim(0.5,1.0)\n",
    "\n",
    "ax.yaxis.grid(True, linestyle='dashed',linewidth=2.5)\n",
    "\n",
    "ax.xaxis.grid(True, linewidth=2)\n",
    "\n",
    "ax.spines['polar'].set_linewidth(2)\n",
    "\n",
    "plt.legend(loc='lower right', bbox_to_anchor=(1.2, -0.1), fontsize=15)\n",
    "\n",
    "plt.savefig(\"image/compare_holdout.png\", dpi=600, bbox_inches='tight')\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "model_names = [model[\"name\"] for model in model_info]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Holdout最优参数"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "import json\n",
    "params_dict = dict(zip(model_names,[x for x in np.array(hold_params_list)[best_auc_indices]]))\n",
    "\n",
    "print(json.dumps(params_dict, indent=4))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Holdout Set 最优模型指标"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "best_holdout_metrics =  np.array(hold_metrics_list)[best_auc_indices]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import (\n",
    "    precision_score, recall_score, f1_score, roc_auc_score,\n",
    "    confusion_matrix\n",
    ")\n",
    "import seaborn as sns\n",
    "\n",
    "\n",
    "model_names = ['SVM', 'AdaBoost', 'RandomForest', 'Stacking']\n",
    "\n",
    "\n",
    "precision_scores = []\n",
    "recall_scores = []\n",
    "f1_scores = []\n",
    "accuracy_scores = []\n",
    "auc_scores = []\n",
    "\n",
    "\n",
    "confusion_matrices = []\n",
    "\n",
    "\n",
    "for model_name in model_names:\n",
    "    model_index = model_names.index(model_name)\n",
    "    y_true = best_holdout_metrics[model_index][0]  \n",
    "    y_pred_prob = best_holdout_metrics[model_index][1] \n",
    "\n",
    "    precision = precision_score(y_true, (y_pred_prob > 0.5).astype(int))\n",
    "    recall = classification_report(y_true, (y_pred_prob > 0.5).astype(int), output_dict=True)['macro avg']['recall']\n",
    "    f1 = f1_score(y_true, (y_pred_prob > 0.5).astype(int))\n",
    "    accuracy = balanced_accuracy_score(y_true, (y_pred_prob > 0.5).astype(int))\n",
    "    auc = roc_auc_score(y_true, y_pred_prob)\n",
    "\n",
    "    precision_scores.append(precision)\n",
    "    recall_scores.append(recall)\n",
    "    f1_scores.append(f1)\n",
    "    accuracy_scores.append(accuracy)\n",
    "    auc_scores.append(auc)\n",
    "\n",
    "\n",
    "    cm = confusion_matrix(y_true, (y_pred_prob > 0.5).astype(int))\n",
    "    confusion_matrices.append(cm)\n",
    "\n",
    "\n",
    "metrics_df = pd.DataFrame({\n",
    "    'Model': model_names,\n",
    "    'Precision': precision_scores,\n",
    "    'Recall': recall_scores,\n",
    "    'F1 Score': f1_scores,\n",
    "    'Balanced_Accurary': accuracy_scores,\n",
    "    'AUC': auc_scores\n",
    "})\n",
    "\n",
    "\n",
    "display(metrics_df)\n",
    "\n",
    "for i, model_name in enumerate(model_names):\n",
    "    plt.figure(figsize=(6, 6))\n",
    "    sns.heatmap(confusion_matrices[i], annot=True, fmt='d', cmap='Blues', cbar=False)\n",
    "    plt.title(f'Confusion Matrix for {model_name}')\n",
    "    plt.xlabel('Predicted')\n",
    "    plt.ylabel('Actual')\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import roc_curve, auc\n",
    "\n",
    "\n",
    "roc_curves = []\n",
    "\n",
    "for model_index, model_name in enumerate(model_names):\n",
    "    y_true = best_holdout_metrics[model_index][0]\n",
    "    y_pred_prob = best_holdout_metrics[model_index][1]\n",
    "\n",
    "    fpr, tpr, _ = roc_curve(y_true, y_pred_prob)\n",
    "    roc_auc = auc(fpr, tpr)\n",
    "\n",
    "    roc_curves.append((fpr, tpr, roc_auc))\n",
    "\n",
    "plt.figure(figsize=(8, 6))\n",
    "for model_index, model_name in enumerate(model_names):\n",
    "    fpr, tpr, roc_auc = roc_curves[model_index]\n",
    "    plt.plot(fpr, tpr, lw=2, label=f'{model_name} (AUC = {roc_auc:.2f})')\n",
    "\n",
    "plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')\n",
    "plt.xlim([0.0, 1.0])\n",
    "plt.ylim([0.0, 1.05])\n",
    "plt.xlabel('False Positive Rate')\n",
    "plt.ylabel('True Positive Rate')\n",
    "plt.title('Receiver Operating Characteristic (ROC) Curve')\n",
    "plt.legend(loc='lower right')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 输出Excel所有指标文件"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import recall_score, roc_auc_score, confusion_matrix\n",
    "import numpy as np\n",
    "\n",
    "def calculate_metrics(y_true, y_pred_prob, threshold=0.5):\n",
    "    y_pred = (y_pred_prob >= threshold).astype(int)\n",
    "\n",
    "    # Sensitivity aka recall\n",
    "    sensitivity = recall_score(y_true, y_pred)\n",
    "\n",
    "    # Specificity\n",
    "    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()\n",
    "    specificity = tn / (tn+fp)\n",
    "\n",
    "    # Balanced Accuracy\n",
    "    balanced_accuracy = (sensitivity + specificity) / 2\n",
    "\n",
    "    # AUC\n",
    "    auc_score = roc_auc_score(y_true, y_pred_prob)\n",
    "\n",
    "    return sensitivity, specificity, balanced_accuracy, auc_score\n",
    "\n",
    "\n",
    "inner_metrics_data = []\n",
    "outer_metrics_data = []\n",
    "hold_metrics_data = []\n",
    "\n",
    "for model_idx, model_name in enumerate(model_names):\n",
    "    for epoch in range(epoch_num):\n",
    "        for outer in range(outer_num):\n",
    "            for inner in range(inner_num):\n",
    "                inner_data = inner_metrics_list[(model_idx * epoch_num * outer_num) + outer_num * epoch + outer]\n",
    "                y_true, y_pred_prob = inner_data\n",
    "                sensitivity, specificity, balanced_accuracy, auc_score = calculate_metrics(y_true, y_pred_prob)\n",
    "\n",
    "                inner_metrics_data.append({\n",
    "                    'Model': model_name,\n",
    "                    'Epoch': epoch + 1,\n",
    "                    'Outer': outer + 1,\n",
    "                    'Inner': inner + 1,\n",
    "                    'Sensitivity': sensitivity,\n",
    "                    'Specificity': specificity,\n",
    "                    'Balanced_Accuracy': balanced_accuracy,\n",
    "                    'AUC': auc_score\n",
    "                })\n",
    "\n",
    "for model_idx, model_name in enumerate(model_names):\n",
    "    for epoch in range(epoch_num):\n",
    "        for outer in range(outer_num):\n",
    "            outer_data = out_metrics_list[(model_idx * epoch_num * outer_num) + outer_num * epoch + outer]\n",
    "            y_true, y_pred_prob = outer_data\n",
    "            sensitivity, specificity, balanced_accuracy, auc_score = calculate_metrics(y_true, y_pred_prob)\n",
    "\n",
    "            outer_metrics_data.append({\n",
    "                'Model': model_name,\n",
    "                'Epoch': epoch + 1,\n",
    "                'Outer': outer + 1,\n",
    "                'Sensitivity': sensitivity,\n",
    "                'Specificity': specificity,\n",
    "                'Balanced_Accuracy': balanced_accuracy,\n",
    "                'AUC': auc_score\n",
    "            })\n",
    "\n",
    "for model_idx, model_name in enumerate(model_names):\n",
    "    for epoch in range(epoch_num):\n",
    "            hold_data = hold_metrics_list[model_idx * epoch_num + epoch]\n",
    "            y_true, y_pred_prob = hold_data\n",
    "            sensitivity, specificity, balanced_accuracy, auc_score = calculate_metrics(y_true, y_pred_prob)\n",
    "            hold_metrics_data.append({\n",
    "                'Model': model_name,\n",
    "                'Epoch': epoch + 1,\n",
    "                'Sensitivity': sensitivity,\n",
    "                'Specificity': specificity,\n",
    "                'Balanced_Accuracy': balanced_accuracy,\n",
    "                'AUC': auc_score\n",
    "            })\n",
    "\n",
    "inner_metrics_df = pd.DataFrame(inner_metrics_data)\n",
    "outer_metrics_df = pd.DataFrame(outer_metrics_data)\n",
    "hold_metrics_df = pd.DataFrame(hold_metrics_data)\n",
    "\n",
    "with pd.ExcelWriter('metrics/model_metrics.xlsx') as writer:\n",
    "    inner_metrics_df.to_excel(writer, sheet_name='InnerMetrics', index=False)\n",
    "    outer_metrics_df.to_excel(writer, sheet_name='OuterMetrics', index=False)\n",
    "    hold_metrics_df.to_excel(writer, sheet_name='HolderMetrics', index=False)\n",
    "\n",
    "print(\"Excel file 'model_metrics.xlsx' saved successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "from tabulate import tabulate\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "model_names = inner_metrics_df['Model'].unique()\n",
    "\n",
    "results_df = pd.DataFrame()\n",
    "\n",
    "\n",
    "def calculate_metrics_average_std(df, model_name):\n",
    "    metrics = df[df['Model'] == model_name]\n",
    "\n",
    "    numeric_metrics = metrics.select_dtypes(include=[np.number])\n",
    "    averages = numeric_metrics.mean()\n",
    "    std_devs = numeric_metrics.std()\n",
    "    results = {'Average': averages, 'Standard Deviation': std_devs}\n",
    "    return results\n",
    "\n",
    "for model_name in model_names:\n",
    "    inner_metrics = calculate_metrics_average_std(inner_metrics_df, model_name)\n",
    "    outer_metrics = calculate_metrics_average_std(outer_metrics_df, model_name)\n",
    "\n",
    "    model_results = {}\n",
    "\n",
    "    for metric in ['Sensitivity', 'Specificity', 'Balanced_Accuracy', 'AUC']:\n",
    "        inner_avg = inner_metrics['Average'][metric]\n",
    "        inner_std = inner_metrics['Standard Deviation'][metric]\n",
    "        outer_avg = outer_metrics['Average'][metric]\n",
    "        outer_std = outer_metrics['Standard Deviation'][metric]\n",
    "\n",
    "        model_results[metric] = f\"{outer_avg:.2f} ± {outer_std:.2f}({inner_avg:.2f} ± {inner_std:.2f})\"\n",
    "\n",
    "    results_df[model_name] = pd.Series(model_results)\n",
    "\n",
    "\n",
    "results_df = results_df.transpose()\n",
    "\n",
    "\n",
    "print(tabulate(results_df, tablefmt=\"pipe\", headers=\"keys\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m无法启动 Kernel。 \n",
      "\u001b[1;31mJupyter Server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/bin/jupyter-notebook\", line 5, in <module>\n",
      "\u001b[1;31m    from notebook.app import main\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/notebook/app.py\", line 12, in <module>\n",
      "\u001b[1;31m    from jupyter_server.base.handlers import JupyterHandler\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n",
      "\u001b[1;31m    from jupyter_events import EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n",
      "\u001b[1;31m    from .logger import EVENTS_METADATA_VERSION, EventLogger\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jupyter_events/logger.py\", line 14, in <module>\n",
      "\u001b[1;31m    from jsonschema import ValidationError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/__init__.py\", line 13, in <module>\n",
      "\u001b[1;31m    from jsonschema._format import FormatChecker\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/_format.py\", line 11, in <module>\n",
      "\u001b[1;31m    from jsonschema.exceptions import FormatError\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/jsonschema/exceptions.py\", line 15, in <module>\n",
      "\u001b[1;31m    from referencing.exceptions import Unresolvable as _Unresolvable\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/__init__.py\", line 4, in <module>\n",
      "\u001b[1;31m    from referencing._core import Anchor, Registry, Resource, Specification\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/referencing/_core.py\", line 8, in <module>\n",
      "\u001b[1;31m    from rpds import HashTrieMap, HashTrieSet, List\n",
      "\u001b[1;31m  File \"/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/__init__.py\", line 1, in <module>\n",
      "\u001b[1;31m    from .rpds import *\n",
      "\u001b[1;31mImportError: dlopen(/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so, 0x0002): tried: '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (no such file), '/Users/zhangtongyi/Library/Python/3.10/lib/python/site-packages/rpds/rpds.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). \n",
      "\u001b[1;31m有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。"
     ]
    }
   ],
   "source": [
    "print(\"全部完成！！\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "biobase",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "c4342b7b77d03aa170c0061ccc2d89deb9ee932a6281860c89ed54b64e098c02"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
